---
dotfiles_repo: https://github.com/theodoorscholte/mac-dotfiles.git
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: ~/mac-dotfiles
dotfiles_repo_version: main # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .aws/config
  - .claude/settings.json
  - .claude/litellm_key.sh

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - nmap
  - node
  - nvm
  - pngpaste
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - pyenv
  - wget
  - wrk
  - zsh-history-substring-search
  - awscli
  - lima
  - uv
  - corepack
  - 1password-cli

homebrew_taps: []

homebrew_cask_apps:
  - signal
  - visual-studio-code
  - zed
  - bitwarden
  - claude-code
  - librewolf



# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps: []

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
